### ISSUE TITLE
Missing License

### ISSUE THREAD

**Issue by v0lta** [RUB-SysSec/GANDCTAnalysis#7]
Dear @Joool ,
without a licence, the only thing people are really allowed to do is look at your code, but no one can ever touch anything.
If that's not what you want please add a license and let everyone know, what, if anything we are allowed to do with your code.
Thanks a lot for your time and consideration,
Moritz

**Comment by Joool** [comment]
https://github.com/RUB-SysSec/GANDCTAnalysis/blob/master/LICENSE

There you go.
